@echo off
echo Starting Cosmocraft Client...
start "Cosmocraft Client" "C:\develop\godot\Godot_v4.5.1-stable_win64.exe\Godot_v4.5.1-stable_win64.exe" --path "C:\develop\Cosmocraft" res://client/main.tscn
